name: lede-r2s-rk3328-openwrt-build-on-self-hosted

on:
  push:
    paths:
      - 'CHANGELOG.md'
env:
  SSH_ACTIONS: false
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: self-hosted
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:

      - name: Assemble Artifact
        id: assemble_artifact
        run: |
          cd lede
          rm -rf artifact.zip
          release_tag="R2S-Lean-$(date +%Y-%m-%d)"
          echo "##[set-output name=release_tag;]$release_tag"
          zip -r artifact.zip ./artifact/

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
           repo_name: szdosar/lede-for-r2s
        # A personal access token for the GitHub repository in which the release will be created and edited.
        # It is recommended to create the access token with the following scopes: `repo, user, admin:repo_hook`.
           repo_token: ${{ secrets.sec_token }}
           file: ./lede/artifact.zip
           asset_name: 发布 ${{ steps.assemble_artifact.outputs.release_tag }}
           tag: ${{ github.ref }}
           overwrite: true
           body: "by dosar"

